---
- name: Install required packages
  yum: name={{item}} state=latest update_cache=yes
  with_items:
    - mc
    - nginx
    - mysql-community-devel
    - git
- name: Install PyMySQLClient
  pip: name=mysqlclient state=present
- name: Add Docker repository
  yum_repository:
    name: docker
    description: Docker YUM repo
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: yes
    enabled: yes
- name: Install Docker engine
  yum: name=docker-engine state=latest update_cache=yes
