
Vagrant.configure(2) do |config|

  config.vm.box = "devops-appserver"

  config.vm.define :dev do |dev|
    dev.vm.network "private_network", ip: "10.100.199.200"
  end

    config.vm.network "forwarded_port", guest: 80, host: 8088

  config.vm.synced_folder "../../html", "/home/vagrant/html", create: true

end

