---
- name: Install wget
  yum: name={{item}} 
  with_items:
    - java-1.8.0-openjdk.x86_64
    - java-1.8.0-openjdk-devel.x86_64

- command: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo
- command: rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Install Jenkins
  yum: name=jenkins state=latest update_cache=yes
